import "./globals.css"
import SideBar  from '@/components/MyComponents/SideBar'
import { SidebarProvider} from "@/components/ui/sidebar"
import CustomToogleSidebar from "@/components/MyComponents/CustomToogleSidebar"

export const metadata = {
  title: 'Fintech Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <SideBar/>
          <main>
            <CustomToogleSidebar/>
          {children}
          </main>
        </SidebarProvider>
        
        </body>
    </html>
  )
}
